### ISSUE TITLE
documentation issue for the docker allinone container

### ISSUE THREAD

**Issue by jave** [maoo/alfresco-boxes#21] opened 2014-10-14 18:46 UTC
So, I used the docker allinone start script to test alfresco.
It starts well, and I can access http://127.0.0.1:8080/share

There the success ends abruptly. I cant figure out the user/pwd.
I tried login in to the created mysql docker container, but it seemed to not contain any tables.

The advertised /alfresco context wasnt available either.

**Comment by maoo** [comment] 2015-02-16 10:08
Hi @jave ; any update on this issue? Can we close it? Or shall we define a list of doc pages to improve (and how)? Thanks!

**Comment by maoo** [comment] 2015-02-19 09:42
Cannot reproduce, closing this issue

**Closed by maoo** 2015-02-19 09:42 UTC
