### ISSUE TITLE
Windows error

### ISSUE THREAD

**Issue by nomisdc** [maoo/alfresco-boxes#16] opened 2014-08-29 19:43 UTC
We seem to get an error trying to install to our windows laptops.  Installed everything to a directory on the D drive.  
We get this error:

$ berks vendor vendor-cookbooks
Resolving cookbook dependencies...
Fetching 'alfresco' from git://github.com/maoo/chef-alfresco.git (at chef-alfresco-0.3.10)
Git error: command `git clone git://github.com/maoo/chef-alfresco.git "c:/Users/SimonHermanez/.berkshelf/.cache/git/90f80cb366ca761830983eb302299d4991
a1ee61" --bare --no-hardlinks` failed. If this error persists, try removing the cache directory at 'c:/Users/SimonHermanez/.berkshelf/.cache/git/90f80
cb366ca761830983eb302299d4991a1ee61'.Output from the command:

Cloning into bare repository 'c:/Users/SimonHermanez/.berkshelf/.cache/git/90f80cb366ca761830983eb302299d4991a1ee61'...
fatal: unable to connect to github.com:
github.com[0: 192.30.252.130]: errno=No such file or directory

Thanks in advance.  Simon

**Comment by maoo** [comment] 2015-02-16 10:11
Hi @nomisdc , any update on this issue? Did you manage to run alfresco-boxes? Please let me know if I can help further of if I can close this issue. Thanks!

**Comment by maoo** [comment] 2015-02-19 09:43
Cannot reproduce, closing issue

**Closed by maoo** 2015-02-19 09:43 UTC
